project_name: circonus-cloud-agent

before:
  hooks:
    - go mod tidy
    - golangci-lint run
    - cmd: golangci-lint run
      env:
        - GOOS=linux
    - govulncheck ./...

builds:
  - id: cca
    main: main.go
    binary: sbin/circonus-cloud-agentd
    env:
      - CGO_ENABLED=0
    flags: -tags dev
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ignore:
      -
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
    ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archives:
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      -
        goos: windows
        format: zip
    files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/README.md

release:
  github:
    owner: circonus-labs
    name: circonus-cloud-agent

  draft: false
  prerelease: auto

changelog:
  use: git
  sort: desc
  abbrev: 0
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Dependencies'
      regexp: "^.*build(deps):+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"

sboms:
  - artifacts: archive
    args: ["$artifact", "--output", "cyclonedx-json@1.5=$document"]
    env:
      - SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES=true
      - SYFT_GOLANG_SEARCH_REMOTE_LICENSES=true
