project_name: circonus-cloud-agent

builds:
  - id: cca
    main: main.go
    binary: sbin/circonus-cloud-agentd
    env:
      - CGO_ENABLED=0
    flags: -tags dev
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ignore:
      -
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
    ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archives:
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    replacements:
      amd64: x86_64
    format_overrides:
      -
        goos: windows
        format: zip
    files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/README.md

release:
  github:
    owner: circonus-labs
    name: circonus-cloud-agent

  draft: false
  prerelease: auto

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
